# npm run build
# gcloud app deploy app.yaml
runtime: nodejs
env: flex

# node version is also specified in package.json: engines.node
# According to https://cloud.google.com/appengine/docs/flexible/nodejs/runtime,
runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
# Minimal sizing for dev/test
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  OCT_FIRE_SETTINGS: 'gs://oct-fire-configs/config-gcp.json'

network:
  name: default
