version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16.16'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
          no_output_timeout: 2m
  lint:
    executor:
      name: node/default
      tag: '16.16'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  format:
    executor:
      name: node/default
      tag: '16.16'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run format
workflows:
  test_my_app:
    jobs:
      - test
      - lint
      - format
